
const authBox=document.querySelector("#authBox"),accountBox=document.querySelector("#accountBox");
document.querySelector("#loginTab").onclick=()=>{document.querySelector("#loginForm").style.display="block";document.querySelector("#registerForm").style.display="none"};
document.querySelector("#registerTab").onclick=()=>{document.querySelector("#loginForm").style.display="none";document.querySelector("#registerForm").style.display="block"};
document.querySelectorAll(".tab-btn[data-tab]").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tab-btn").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".tab-panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelector("#"+b.dataset.tab).classList.add("active")}));
async function me(){try{const d=await api("/auth/me");if(!d.user)throw 0;authBox.style.display="none";accountBox.style.display="block";document.querySelector("#welcome").textContent=`Olá, ${d.user.name}.`;document.querySelector("#profileName").value=d.user.name||"";document.querySelector("#profilePhone").value=d.user.phone||"";await refreshAccount()}catch{authBox.style.display="block";accountBox.style.display="none"}}
async function refreshAccount(){const d=await api("/account");document.querySelector("#addressList").innerHTML=(d.addresses||[]).map(a=>`<div class="panel" style="margin-bottom:8px;padding:12px"><strong>${esc(a.line)}</strong><div class="msg">${esc(a.city)} · ${esc(a.cep)}</div></div>`).join("")||'<p class="msg">Nenhum endereço cadastrado.</p>';document.querySelector("#favoriteList").innerHTML=(d.favorites||[]).map(p=>`<a class="panel" style="display:block;margin-bottom:8px;padding:12px" href="produto.html?id=${encodeURIComponent(p.id)}"><strong>${esc(p.name)}</strong><div class="msg">${brl(p.price)}</div></a>`).join("")||'<p class="msg">Nenhum favorito ainda.</p>';document.querySelector("#orderList").innerHTML=(d.orders||[]).map(o=>`<div class="panel" style="margin-bottom:8px;padding:12px"><strong>Pedido #${o.id}</strong><div class="msg">${esc(o.status)} · ${brl(o.total)}</div></div>`).join("")||'<p class="msg">Nenhum pedido registrado.</p>'}
document.querySelector("#loginForm").onsubmit=async e=>{e.preventDefault();try{await api("/auth/login",{method:"POST",body:JSON.stringify({login:document.querySelector("#loginEmail").value,password:document.querySelector("#loginPassword").value})});me()}catch(err){document.querySelector("#authMsg").textContent=err.message;document.querySelector("#authMsg").className="msg error"}};
document.querySelector("#registerForm").onsubmit=async e=>{e.preventDefault();try{await api("/auth/register",{method:"POST",body:JSON.stringify({name:document.querySelector("#regName").value,email:document.querySelector("#regEmail").value,phone:document.querySelector("#regPhone").value,password:document.querySelector("#regPassword").value})});me()}catch(err){document.querySelector("#authMsg").textContent=err.message;document.querySelector("#authMsg").className="msg error"}};
document.querySelector("#logoutBtn").onclick=async()=>{await api("/auth/logout",{method:"POST",body:"{}"});location.reload()};
document.querySelector("#profileForm").onsubmit=async e=>{e.preventDefault();await api("/account/profile",{method:"PATCH",body:JSON.stringify({name:document.querySelector("#profileName").value,phone:document.querySelector("#profilePhone").value})});await me()};
document.querySelector("#addressForm").onsubmit=async e=>{e.preventDefault();await api("/account/addresses",{method:"POST",body:JSON.stringify({cep:document.querySelector("#addrCep").value,line:document.querySelector("#addrLine").value,city:document.querySelector("#addrCity").value})});e.target.reset();refreshAccount()};
me();
