const id=new URLSearchParams(location.search).get('id');
async function load(){
 let p;try{p=normalizeProduct((await api(`/products/${encodeURIComponent(id)}`)).product)}catch(e){p=productFallback().map(normalizeProduct).find(x=>x.id===id)}
 if(!p){$('#productView').innerHTML='<div class="panel">Produto não encontrado.</div>';return}
 const specs=Array.isArray(p.specs)?p.specs:[],gallery=[p.image_url,...(p.gallery||[])].filter((x,i,a)=>x&&a.indexOf(x)===i).slice(0,8);document.title=`${p.name} | Marcell Celular`;
 $('#productView').innerHTML=`<section><div class="gallery-main"><img id="mainProductImage" src="${esc(gallery[0])}" alt="${esc(p.name)}" style="object-position:${p.image_position_x}% ${p.image_position_y}%"></div><div class="thumbs">${gallery.map((g,i)=>`<button type="button" data-gallery="${esc(g)}" aria-label="Imagem ${i+1}"><img src="${esc(g)}" alt=""></button>`).join('')}</div></section><section class="product-info"><span class="eyebrow" style="color:var(--brand);background:var(--panel-2);border-color:var(--line)">${esc(p.brand)} · ${esc(p.condition)}</span><h1>${esc(p.name)}</h1><p class="lead">${esc(p.storage||'')} · ${esc(p.color||'')} · ${p.stock>0?`${p.stock} unidade(s) em estoque`:'Sob consulta'}</p><div class="price" style="font-size:2rem">${brl(p.price)} ${p.old_price?`<small><s>${brl(p.old_price)}</s></small>`:''}</div>${p.installments>1?`<div class="price-breakdown"><span class="price-chip">até ${p.installments}x de ${brl(p.price/p.installments)}</span>${p.old_price?`<span class="price-chip">economia de ${brl(p.old_price-p.price)}</span>`:''}</div>`:''}${p.wholesale_price?`<div class="shipping"><strong>Preço para revenda</strong><p class="msg">${brl(p.wholesale_price)} por unidade a partir de ${p.wholesale_min_qty} unidades. Consulte disponibilidade para volume.</p></div>`:''}<div class="specs">${specs.map(s=>`<div class="spec"><small>${esc(s[0])}</small><strong>${esc(s[1])}</strong></div>`).join('')}</div><div class="panel" style="padding:14px;margin-top:12px"><strong>Condição e garantia</strong><div class="msg" style="margin-top:6px">Garantia informada: ${p.warranty_days||0} dias${p.battery_health!=null?` · Saúde da bateria: ${p.battery_health}%`:''}${p.includes_box?' · Com caixa':''}${p.includes_charger?' · Com carregador':''}</div></div><div class="shipping"><strong>Calcular frete</strong><p class="msg">Informe seu CEP para consultar serviços habilitados.</p><form class="shipping-form" id="shippingForm"><input id="cep" inputmode="numeric" maxlength="9" placeholder="00000-000" required><button class="btn btn-brand">Calcular</button></form><div id="shippingResult" class="shipping-result"></div></div><div class="hero-actions"><a class="btn btn-primary" target="_blank" href="https://wa.me/5584998701100?text=${encodeURIComponent(`Olá! Tenho interesse no ${p.name} (${p.storage||''}).`)}">Comprar pelo WhatsApp</a><button class="btn btn-ghost" id="favoriteBtn">♡ Favoritar</button></div></section>`;
 document.querySelectorAll('[data-gallery]').forEach(b=>b.addEventListener('click',()=>$('#mainProductImage').src=b.dataset.gallery));
 $('#shippingForm').addEventListener('submit',async e=>{e.preventDefault();const out=$('#shippingResult');out.textContent='Consultando...';try{const data=await api('/shipping',{method:'POST',body:JSON.stringify({cep:$('#cep').value,product_id:p.id})});out.innerHTML=data.options.map(x=>`<div class="shipping-option"><span><strong>${esc(x.service)}</strong><br><small>${esc(x.deadline)}</small></span><strong>${brl(x.price)}</strong></div>`).join('')}catch(err){out.innerHTML=`<span class="error">${esc(err.message)}</span><br><small>Retirada na loja continua disponível.</small>`}});
 $('#favoriteBtn').addEventListener('click',async()=>{try{await api('/account/favorites',{method:'POST',body:JSON.stringify({product_id:p.id})});$('#favoriteBtn').textContent='♥ Salvo'}catch(err){location.href='conta.html'}})
}
load();
