let catalog=[], selectedBrand="";
async function loadCatalog(){try{catalog=(await api('/products')).products.map(normalizeProduct)}catch(e){catalog=productFallback().map(normalizeProduct)}render()}
function render(){
  const q=($('#q')?.value||'').trim().toLowerCase(),cond=$('#conditionFilter')?.value||'',sort=$('#sortFilter')?.value||'featured';
  let list=catalog.filter(p=>p.active!==0&&(!selectedBrand||p.brand===selectedBrand)&&(!cond||p.condition===cond)&&(!q||`${p.brand} ${p.name} ${p.storage} ${p.color||''}`.toLowerCase().includes(q)));
  if(sort==='low')list.sort((a,b)=>a.price-b.price);else if(sort==='high')list.sort((a,b)=>b.price-a.price);else list.sort((a,b)=>(b.featured||0)-(a.featured||0));
  $('#products').innerHTML=list.map(p=>`<article class="product-card"><a class="product-media" href="produto.html?id=${encodeURIComponent(p.id)}"><img src="${esc(p.image_url)}" alt="${esc(p.name)}" style="object-position:${p.image_position_x}% ${p.image_position_y}%"><span class="tag">${p.stock>0?`${p.stock} em estoque`:'Consultar'}</span></a><div class="product-body"><div class="product-meta"><span>${esc(p.brand)}</span><span>${esc(p.condition)} · ${esc(p.storage||'')}</span></div><h3>${esc(p.name)}</h3><div class="price">${brl(p.price)} ${p.old_price?`<small><s>${brl(p.old_price)}</s></small>`:''}</div>${p.installments>1?`<div class="preview-extra">até ${p.installments}x de ${brl(p.price/p.installments)}</div>`:''}${p.wholesale_price?`<div class="preview-extra wholesale-preview">Atacado ${brl(p.wholesale_price)} · mín. ${p.wholesale_min_qty}</div>`:''}<div class="card-actions"><a class="btn btn-ghost" href="produto.html?id=${encodeURIComponent(p.id)}">Ver detalhes</a><a class="btn btn-primary" target="_blank" href="https://wa.me/5584998701100?text=${encodeURIComponent(`Olá! Vi o ${p.name} no site e gostaria de confirmar disponibilidade.`)}">Comprar</a></div></div></article>`).join('')||'<div class="panel">Nenhum produto encontrado.</div>';
}
$('#globalSearch')?.addEventListener('submit',e=>{e.preventDefault();render();$('#catalogo').scrollIntoView({behavior:'smooth'})});$('#conditionFilter')?.addEventListener('change',render);$('#sortFilter')?.addEventListener('change',render);document.querySelectorAll('.brand-filter[data-brand]').forEach(b=>b.addEventListener('click',()=>{selectedBrand=b.dataset.brand;document.querySelectorAll('.brand-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()}));$('#brandToggle')?.addEventListener('click',()=>$('#sidebar').classList.toggle('open'));loadCatalog();
