const KEY_PRODUCTS='marlon_products_v1',KEY_CART='marlon_cart_v1',KEY_USERS='marlon_users_v1',KEY_SESSION='marlon_session_v1',KEY_COOKIES='marlon_cookie_consent_v1';
const defaults=[
{id:'p1',name:'iPhone 15 Pro 256GB',brand:'Apple',category:'smartphone',condition:'new',price:6999,oldPrice:7399,stock:4,icon:'📱',note:'Novo • 12 meses de garantia'},
{id:'p2',name:'Galaxy S24 Ultra 256GB',brand:'Samsung',category:'smartphone',condition:'new',price:5899,oldPrice:6299,stock:7,icon:'📱',note:'Novo • Nota fiscal'},
{id:'p3',name:'iPhone 13 128GB',brand:'Apple',category:'smartphone',condition:'used',price:2899,oldPrice:3299,stock:2,icon:'📱',note:'Seminovo • Bateria 88% • Garantia 90 dias'},
{id:'p4',name:'MacBook Air M2 256GB',brand:'Apple',category:'notebook',condition:'used',price:5990,oldPrice:6490,stock:1,icon:'💻',note:'Seminovo • Excelente estado'},
{id:'p5',name:'Notebook Galaxy Book4',brand:'Samsung',category:'notebook',condition:'new',price:4199,oldPrice:4499,stock:5,icon:'💻',note:'Novo • Intel Core 5'},
{id:'p6',name:'Headphone WH-1000XM5',brand:'Sony',category:'audio',condition:'new',price:2199,oldPrice:2399,stock:3,icon:'🎧',note:'Novo • Cancelamento de ruído'},
{id:'p7',name:'PlayStation 5 Slim',brand:'Sony',category:'game',condition:'new',price:3799,oldPrice:3999,stock:6,icon:'🎮',note:'Novo • 1 controle'},
{id:'p8',name:'Apple Watch Series 9',brand:'Apple',category:'smartwatch',condition:'used',price:2190,oldPrice:2490,stock:2,icon:'⌚',note:'Seminovo • Caixa 45 mm'}
];
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);
const qs=(s,r=document)=>r.querySelector(s),qsa=(s,r=document)=>[...r.querySelectorAll(s)];
function products(){let p=JSON.parse(localStorage.getItem(KEY_PRODUCTS)||'null');if(!p){p=defaults;localStorage.setItem(KEY_PRODUCTS,JSON.stringify(p))}return p}
let activeFilter='all',categoryFilter='all';
function renderProducts(){const term=(qs('#searchInput')?.value||'').toLowerCase();const list=products().filter(p=>(activeFilter==='all'||p.condition===activeFilter)&&(categoryFilter==='all'||p.category===categoryFilter)&&(`${p.name} ${p.brand}`.toLowerCase().includes(term)));qs('#productGrid').innerHTML=list.map(p=>`<article class="product" data-product><div class="product-media"><span class="condition ${p.condition}">${p.condition==='new'?'NOVO':'SEMINOVO'}</span><span class="stock">${p.stock>0?`${p.stock} em estoque`:'Esgotado'}</span><div class="product-art">${p.icon}</div></div><div class="product-body"><div class="product-brand">${p.brand}</div><div class="product-title">${p.name}</div><div><span class="price">${money(p.price)}</span>${p.oldPrice?`<span class="old-price">${money(p.oldPrice)}</span>`:''}</div><div class="product-meta"><span>${p.note}</span></div><div class="product-actions"><button class="btn primary" data-add="${p.id}" ${p.stock<1?'disabled':''}>${p.stock<1?'Sem estoque':'Adicionar'}</button></div></div></article>`).join('')||'<p class="muted">Nenhum produto encontrado.</p>';qsa('[data-add]').forEach(b=>b.onclick=()=>addCart(b.dataset.add));updateStats();animateNewCards()}
function getCart(){return JSON.parse(localStorage.getItem(KEY_CART)||'[]')}
function saveCart(c){localStorage.setItem(KEY_CART,JSON.stringify(c));renderCart()}
function addCart(id){const p=products().find(x=>x.id===id);if(!p||p.stock<1)return;let c=getCart();const row=c.find(x=>x.id===id);if(row)row.qty=Math.min(row.qty+1,p.stock);else c.push({id,qty:1});saveCart(c);openCart()}
function renderCart(){const c=getCart(),ps=products();qs('[data-cart-count]').textContent=c.reduce((a,b)=>a+b.qty,0);let subtotal=0;qs('#cartItems').innerHTML=c.length?c.map(row=>{const p=ps.find(x=>x.id===row.id);if(!p)return'';subtotal+=p.price*row.qty;return`<div class="cart-item"><div class="cart-thumb">${p.icon}</div><div><b>${p.name}</b><div class="muted" style="font-size:.8rem">${money(p.price)}</div><div class="qty"><button data-qty="${p.id}" data-delta="-1">−</button><span>${row.qty}</span><button data-qty="${p.id}" data-delta="1">+</button></div></div><button class="btn small ghost" data-remove="${p.id}">Remover</button></div>`}).join(''):'<p class="muted">Seu carrinho está vazio.</p>';qs('#cartSubtotal').textContent=money(subtotal);qsa('[data-qty]').forEach(b=>b.onclick=()=>changeQty(b.dataset.qty,+b.dataset.delta));qsa('[data-remove]').forEach(b=>b.onclick=()=>removeCart(b.dataset.remove))}
function changeQty(id,d){let c=getCart(),p=products().find(x=>x.id===id),r=c.find(x=>x.id===id);if(!r)return;r.qty=Math.max(0,Math.min(r.qty+d,p?.stock||0));c=c.filter(x=>x.qty>0);saveCart(c)}function removeCart(id){saveCart(getCart().filter(x=>x.id!==id))}
const drawer=qs('#cartDrawer');function openCart(){drawer.classList.add('open');drawer.setAttribute('aria-hidden','false')}function closeCart(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true')}qsa('[data-open-cart]').forEach(x=>x.onclick=openCart);qsa('[data-close-cart]').forEach(x=>x.onclick=closeCart);
qs('#calcShipping').onclick=async()=>{let cep=qs('#cepInput').value.replace(/\D/g,'');const box=qs('#shippingResult');if(cep.length!==8){box.innerHTML='<span style="color:#ff9dae">Digite um CEP válido.</span>';return}box.innerHTML='<span class="muted">Consultando CEP…</span>';let city='seu endereço';try{const r=await fetch(`https://viacep.com.br/ws/${cep}/json/`);const d=await r.json();if(!d.erro)city=`${d.localidade}/${d.uf}`}catch{}const subtotal=getCart().reduce((s,r)=>{const p=products().find(x=>x.id===r.id);return s+(p?p.price*r.qty:0)},0);const std=subtotal>=1500?0:29.9,exp=std===0?24.9:49.9;box.innerHTML=`<div class="ship-option"><span>Padrão • 5–9 dias<br><small class="muted">Entrega para ${city}</small></span><b>${std===0?'Grátis':money(std)}</b></div><div class="ship-option"><span>Expresso • 2–4 dias<br><small class="muted">Estimativa demonstrativa</small></span><b>${money(exp)}</b></div>`};
qs('#checkoutDemo').onclick=()=>alert('Checkout demonstrativo. Na produção, esta etapa será conectada ao gateway de pagamento, antifraude e frete real.');
qsa('[data-filter]').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;qsa('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderProducts()});qs('#searchInput').addEventListener('input',renderProducts);qsa('[data-category]').forEach(a=>a.onclick=()=>{categoryFilter=a.dataset.category;setTimeout(renderProducts)});
function updateStats(){const ps=products();qs('[data-stat-products]').textContent=ps.length;qs('[data-stat-stock]').textContent=ps.reduce((s,p)=>s+p.stock,0);qs('[data-stat-low]').textContent=ps.filter(p=>p.stock<=2).length}
const auth=qs('#authModal');qsa('[data-open-auth]').forEach(x=>x.onclick=e=>{e.preventDefault();auth.classList.add('open')});qsa('[data-close-auth]').forEach(x=>x.onclick=()=>auth.classList.remove('open'));qsa('[data-auth-tab]').forEach(t=>t.onclick=()=>{qsa('[data-auth-tab]').forEach(x=>x.classList.toggle('active',x===t));qs('#loginForm').hidden=t.dataset.authTab!=='login';qs('#registerForm').hidden=t.dataset.authTab!=='register';qs('#authTitle').textContent=t.dataset.authTab==='login'?'Entre na sua conta':'Crie sua conta'});
async function hash(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
qs('#registerForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),email=fd.get('email').trim().toLowerCase(),users=JSON.parse(localStorage.getItem(KEY_USERS)||'[]'),st=qs('#registerStatus');if(users.some(u=>u.email===email)){st.className='status-msg err';st.textContent='Este e-mail já foi cadastrado neste navegador.';return}users.push({name:fd.get('name').trim(),email,pass:await hash(fd.get('password'))});localStorage.setItem(KEY_USERS,JSON.stringify(users));localStorage.setItem(KEY_SESSION,JSON.stringify({email,name:fd.get('name').trim()}));st.className='status-msg ok';st.textContent='Conta criada. Você já está conectado.';setTimeout(()=>auth.classList.remove('open'),700)};
qs('#loginForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),email=fd.get('email').trim().toLowerCase(),pass=await hash(fd.get('password')),u=JSON.parse(localStorage.getItem(KEY_USERS)||'[]').find(x=>x.email===email&&x.pass===pass),st=qs('#loginStatus');if(!u){st.className='status-msg err';st.textContent='E-mail ou senha não encontrados neste navegador.';return}localStorage.setItem(KEY_SESSION,JSON.stringify({email:u.email,name:u.name}));st.className='status-msg ok';st.textContent=`Bem-vindo, ${u.name}.`;setTimeout(()=>auth.classList.remove('open'),650)};
// Cookies / LGPD
const cb=qs('#cookieBanner'),cm=qs('#cookieModal');function pref(){return JSON.parse(localStorage.getItem(KEY_COOKIES)||'null')}function savePref(v){localStorage.setItem(KEY_COOKIES,JSON.stringify({...v,necessary:true,updatedAt:new Date().toISOString()}));cb.classList.remove('show');cm.classList.remove('open')}if(!pref())setTimeout(()=>cb.classList.add('show'),650);qsa('[data-cookie-accept]').forEach(x=>x.onclick=()=>savePref({analytics:true,marketing:true}));qsa('[data-cookie-reject]').forEach(x=>x.onclick=()=>savePref({analytics:false,marketing:false}));qsa('[data-cookie-custom],[data-cookie-prefs]').forEach(x=>x.onclick=e=>{e.preventDefault();const p=pref()||{};qs('#cookieAnalytics').checked=!!p.analytics;qs('#cookieMarketing').checked=!!p.marketing;cm.classList.add('open')});qsa('[data-cookie-close]').forEach(x=>x.onclick=()=>cm.classList.remove('open'));qsa('[data-cookie-save]').forEach(x=>x.onclick=()=>savePref({analytics:qs('#cookieAnalytics').checked,marketing:qs('#cookieMarketing').checked}));
async function motion(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;try{const {animate,inView,stagger}=await import('https://cdn.jsdelivr.net/npm/motion@11.18.2/+esm');animate('.hero .eyebrow,.hero h1,.hero-copy,.hero-actions,.trust-row',{opacity:[0,1],y:[28,0]},{delay:stagger(.09),duration:.65,ease:'easeOut'});inView('.section-head, .feature-card, .cta',(el)=>animate(el,{opacity:[0,1],y:[32,0]},{duration:.55,ease:'easeOut'}),{margin:'-10% 0px'});window.__marlonAnimate=animate}catch(e){console.info('Motion.js indisponível; experiência base preservada.')}}function animateNewCards(){if(window.__marlonAnimate&&!matchMedia('(prefers-reduced-motion: reduce)').matches)window.__marlonAnimate('[data-product]',{opacity:[0,1],y:[20,0]},{duration:.35,delay:0.03})}
renderProducts();renderCart();motion();
